# Generated by Django 4.2.1 on 2023-06-11 06:38

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rock",
            fields=[
                ("rock_id", models.IntegerField(primary_key=True, serialize=False)),
                ("rock_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("gender", models.IntegerField(default=1)),
                ("spec", models.CharField(default="", max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="custom_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Rock9",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stopeMethod", models.CharField(max_length=255)),
                ("stopeOreCaving", models.CharField(max_length=255)),
                ("stopeHoleLayout", models.CharField(max_length=255)),
                ("stopeBoreholeDiameter", models.FloatField(null=True)),
                ("stopeDistance", models.FloatField(null=True)),
                ("stopeArrayPitch", models.FloatField(null=True)),
                ("stopeExplosiveType", models.CharField(max_length=255)),
                ("stopeSpecificCharge", models.FloatField(null=True)),
                ("stopeSublevelHeight", models.FloatField(null=True)),
                ("stopeDriftInterval", models.FloatField(null=True)),
                ("stopeCollapseStepDistance", models.FloatField(null=True)),
                ("stopeEdgeHoleAngle", models.FloatField(null=True)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rock8",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excavationSectionShape", models.CharField(max_length=255)),
                ("excavationSectionArea", models.FloatField(null=True)),
                ("excavationCutForm", models.CharField(max_length=255)),
                ("excavationHollowholeDiameter", models.FloatField(null=True)),
                ("excavationBoreholeDiameter", models.FloatField(null=True)),
                ("excavationBoreholeNumber", models.FloatField(null=True)),
                ("excavationCutCharge", models.FloatField(null=True)),
                ("excavationExplosiveType", models.CharField(max_length=255)),
                ("excavationSpecificCharge", models.FloatField(null=True)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rock7",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rockStaticStrength", models.FloatField(null=True)),
                ("rockProctorsCoefficient", models.FloatField(null=True)),
                ("rockDynamicStrength", models.FloatField(null=True)),
                ("surfaceHoleLayout", models.CharField(max_length=255)),
                ("surfaceBoreDiameter", models.FloatField(null=True)),
                ("surfaceHoleDepth", models.FloatField(null=True)),
                ("surfaceDistance", models.FloatField(null=True)),
                ("surfaceArrayPitch", models.FloatField(null=True)),
                ("surfaceSuperDeep", models.FloatField(null=True)),
                ("surfaceExplosiveType", models.CharField(max_length=255)),
                ("surfaceSpecificCharge", models.FloatField(null=True)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rock6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xrdMineralContent", models.CharField(max_length=255)),
                ("xrdPattern", models.CharField(max_length=255)),
                ("xrdJade", models.CharField(max_length=255)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rock5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shearingStrength", models.FloatField(null=True)),
                ("shearStressShearDirection", models.CharField(max_length=255)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rock4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tensileStrength", models.FloatField(null=True)),
                ("tensileFailureLoad", models.FloatField(null=True)),
                ("tensileFailureMode", models.CharField(max_length=255)),
                ("tensileAxialLoad", models.CharField(max_length=255)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rock3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triaxialCompressiveStrength", models.FloatField(null=True)),
                ("rockCohesion", models.FloatField(null=True)),
                ("rockInternalFrictionAngle", models.FloatField(null=True)),
                ("youngModulus", models.FloatField(null=True)),
                ("poissonsRatio", models.FloatField(null=True)),
                ("triaxialFailureMode", models.CharField(max_length=255)),
                ("triaxialStressStrainCurve", models.CharField(max_length=255)),
                ("triaxialMohrStrength", models.CharField(max_length=255)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rock2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uniaxialCompressiveStrength", models.FloatField(null=True)),
                ("elasticModulus", models.FloatField(null=True)),
                ("poissonsRatio", models.FloatField(null=True)),
                ("uniaxialFailureMode", models.CharField(max_length=255)),
                ("uniaxialStressStrainCurve", models.CharField(max_length=255)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rock1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rockType", models.CharField(max_length=255)),
                ("rockDensity", models.CharField(max_length=255)),
                ("rockPorosity", models.CharField(max_length=255)),
                ("rockWaterAbsorption", models.CharField(max_length=255)),
                ("rockPermeabilityCoefficient", models.CharField(max_length=255)),
                ("rockLongitudinalWaveVelocity", models.CharField(max_length=255)),
                ("rockTransverseWaveVelocity", models.CharField(max_length=255)),
                ("rockWaveImpedance", models.FloatField(null=True)),
                ("rockOrigin", models.CharField(max_length=255)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataBaseApp.rock",
                    ),
                ),
            ],
        ),
    ]
