# Generated by Django 4.2.1 on 2023-06-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataBaseApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rock",
            name="rock_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
