# Generated by Django 4.2.2 on 2023-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dataBaseApp",
            "0003_remove_rock1_id_remove_rock2_id_remove_rock3_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rock1",
            name="rockType",
            field=models.CharField(
                choices=[("1", "选项1"), ("2", "选项2"), ("3", "选项3")], max_length=255
            ),
        ),
    ]
