# Generated by Django 4.1.3 on 2023-07-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0007_alter_rock1_rockdensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock1',
            name='rockWaveImpedance',
            field=models.CharField(max_length=255, null=True, verbose_name='波阻抗'),
        ),
    ]
