# Generated by Django 4.2.2 on 2023-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataBaseApp", "0008_alter_rock1_rockwaveimpedance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rock1",
            name="rockDensity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="密度"
            ),
        ),
        migrations.AlterField(
            model_name="rock1",
            name="rockLongitudinalWaveVelocity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="纵波速度"
            ),
        ),
        migrations.AlterField(
            model_name="rock1",
            name="rockOrigin",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="岩石产地"
            ),
        ),
        migrations.AlterField(
            model_name="rock1",
            name="rockPermeabilityCoefficient",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="渗透系数"
            ),
        ),
        migrations.AlterField(
            model_name="rock1",
            name="rockPorosity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="孔隙度"
            ),
        ),
        migrations.AlterField(
            model_name="rock1",
            name="rockTransverseWaveVelocity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="横波速度"
            ),
        ),
        migrations.AlterField(
            model_name="rock1",
            name="rockWaterAbsorption",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="吸水率"
            ),
        ),
        migrations.AlterField(
            model_name="rock1",
            name="rockWaveImpedance",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="波阻抗"
            ),
        ),
        migrations.AlterField(
            model_name="rock2",
            name="elasticModulus",
            field=models.FloatField(blank=True, null=True, verbose_name="弹性模量"),
        ),
        migrations.AlterField(
            model_name="rock2",
            name="poissonsRatio",
            field=models.FloatField(blank=True, null=True, verbose_name="泊松比"),
        ),
        migrations.AlterField(
            model_name="rock2",
            name="uniaxialCompressiveStrength",
            field=models.FloatField(blank=True, null=True, verbose_name="单轴抗压强度"),
        ),
        migrations.AlterField(
            model_name="rock2",
            name="uniaxialFailureMode",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="单轴破坏模式（图）"
            ),
        ),
        migrations.AlterField(
            model_name="rock2",
            name="uniaxialStressStrainCurve",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="单轴应力-应变曲线（图）"
            ),
        ),
        migrations.AlterField(
            model_name="rock3",
            name="poissonsRatio",
            field=models.FloatField(blank=True, null=True, verbose_name="泊松比"),
        ),
        migrations.AlterField(
            model_name="rock3",
            name="rockCohesion",
            field=models.FloatField(blank=True, null=True, verbose_name="内聚力"),
        ),
        migrations.AlterField(
            model_name="rock3",
            name="rockInternalFrictionAngle",
            field=models.FloatField(blank=True, null=True, verbose_name="内摩擦角"),
        ),
        migrations.AlterField(
            model_name="rock3",
            name="triaxialCompressiveStrength",
            field=models.FloatField(blank=True, null=True, verbose_name="三轴抗压强度"),
        ),
        migrations.AlterField(
            model_name="rock3",
            name="triaxialFailureMode",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="三轴破坏模式（图）"
            ),
        ),
        migrations.AlterField(
            model_name="rock3",
            name="triaxialMohrStrength",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="三轴莫尔强度包络图（图）"
            ),
        ),
        migrations.AlterField(
            model_name="rock3",
            name="triaxialStressStrainCurve",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="三轴应力-应变曲线（图）"
            ),
        ),
        migrations.AlterField(
            model_name="rock3",
            name="youngModulus",
            field=models.FloatField(blank=True, null=True, verbose_name="杨氏模量"),
        ),
        migrations.AlterField(
            model_name="rock4",
            name="tensileAxialLoad",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                verbose_name="抗拉强度轴向-荷载位移图（图）",
            ),
        ),
        migrations.AlterField(
            model_name="rock4",
            name="tensileFailureLoad",
            field=models.FloatField(blank=True, null=True, verbose_name="破坏荷载"),
        ),
        migrations.AlterField(
            model_name="rock4",
            name="tensileFailureMode",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="抗拉强度破坏模式（图）"
            ),
        ),
        migrations.AlterField(
            model_name="rock4",
            name="tensileStrength",
            field=models.FloatField(blank=True, null=True, verbose_name="抗拉强度"),
        ),
        migrations.AlterField(
            model_name="rock5",
            name="shearStressShearDirection",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                verbose_name="剪切应力-剪切方向位移（图）",
            ),
        ),
        migrations.AlterField(
            model_name="rock5",
            name="shearingStrength",
            field=models.FloatField(blank=True, null=True, verbose_name="抗剪强度"),
        ),
        migrations.AlterField(
            model_name="rock6",
            name="xrdJade",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="Jade定量分析"
            ),
        ),
        migrations.AlterField(
            model_name="rock6",
            name="xrdMineralContent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="主要矿物含量"
            ),
        ),
        migrations.AlterField(
            model_name="rock6",
            name="xrdPattern",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="XRD衍射图谱"
            ),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="rockDynamicStrength",
            field=models.FloatField(blank=True, null=True, verbose_name="岩石动态强度"),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="rockProctorsCoefficient",
            field=models.FloatField(blank=True, null=True, verbose_name="普氏系数"),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="rockStaticStrength",
            field=models.FloatField(blank=True, null=True, verbose_name="岩石静态强度"),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="surfaceArrayPitch",
            field=models.FloatField(blank=True, null=True, verbose_name="露天排距/抵抗线"),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="surfaceBoreDiameter",
            field=models.FloatField(blank=True, null=True, verbose_name="露天孔径"),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="surfaceDistance",
            field=models.FloatField(blank=True, null=True, verbose_name="露天孔距"),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="surfaceExplosiveType",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="露天炸药类型"
            ),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="surfaceHoleDepth",
            field=models.FloatField(blank=True, null=True, verbose_name="露天孔深"),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="surfaceHoleLayout",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="露天炮孔布置"
            ),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="surfaceSpecificCharge",
            field=models.FloatField(blank=True, null=True, verbose_name="露天炸药单耗"),
        ),
        migrations.AlterField(
            model_name="rock7",
            name="surfaceSuperDeep",
            field=models.FloatField(blank=True, null=True, verbose_name="露天超深"),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationBoreholeDiameter",
            field=models.FloatField(blank=True, null=True, verbose_name="炮孔直径"),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationBoreholeNumber",
            field=models.FloatField(blank=True, null=True, verbose_name="炮孔数量"),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationCutCharge",
            field=models.FloatField(blank=True, null=True, verbose_name="掏槽单耗"),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationCutForm",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="掏槽形式"
            ),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationExplosiveType",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="炸药类型"
            ),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationHollowholeDiameter",
            field=models.FloatField(blank=True, null=True, verbose_name="空孔直径"),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationSectionArea",
            field=models.FloatField(blank=True, null=True, verbose_name="断面面积"),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationSectionShape",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="断面形状"
            ),
        ),
        migrations.AlterField(
            model_name="rock8",
            name="excavationSpecificCharge",
            field=models.FloatField(blank=True, null=True, verbose_name="掘进炸药单耗"),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeArrayPitch",
            field=models.FloatField(blank=True, null=True, verbose_name="排距/最小抵抗线"),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeBoreholeDiameter",
            field=models.FloatField(blank=True, null=True, verbose_name="炮孔直径"),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeCollapseStepDistance",
            field=models.FloatField(blank=True, null=True, verbose_name="崩矿步距"),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeDistance",
            field=models.FloatField(blank=True, null=True, verbose_name="孔距/孔底距"),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeDriftInterval",
            field=models.FloatField(blank=True, null=True, verbose_name="进路间距"),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeEdgeHoleAngle",
            field=models.FloatField(blank=True, null=True, verbose_name="边孔角"),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeHoleLayout",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="炮孔布置形式"
            ),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeMethod",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="采矿方法"
            ),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeOreCaving",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="落矿方式"
            ),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeSpecificCharge",
            field=models.FloatField(blank=True, null=True, verbose_name="回采炸药单耗"),
        ),
        migrations.AlterField(
            model_name="rock9",
            name="stopeSublevelHeight",
            field=models.FloatField(blank=True, null=True, verbose_name="分段高度"),
        ),
    ]
