# Generated by Django 4.1.3 on 2023-07-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0012_alter_rock3_poissonsratio_alter_rock3_rockcohesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock7',
            name='surfaceArrayPitch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='排距/抵抗线'),
        ),
        migrations.AlterField(
            model_name='rock7',
            name='surfaceBoreDiameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='孔径'),
        ),
        migrations.AlterField(
            model_name='rock7',
            name='surfaceDistance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='孔距'),
        ),
        migrations.AlterField(
            model_name='rock7',
            name='surfaceHoleDepth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='孔深'),
        ),
        migrations.AlterField(
            model_name='rock7',
            name='surfaceSuperDeep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='超深'),
        ),
        migrations.AlterField(
            model_name='rock8',
            name='excavationSpecificCharge',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='炸药单耗'),
        ),
    ]
