# Generated by Django 4.1.3 on 2023-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0013_remove_rock5_rockcohesion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock7',
            name='surfaceArrayPitch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='露天排距/抵抗线'),
        ),
        migrations.AlterField(
            model_name='rock7',
            name='surfaceBoreDiameter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='露天孔径'),
        ),
        migrations.AlterField(
            model_name='rock7',
            name='surfaceDistance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='露天孔距'),
        ),
        migrations.AlterField(
            model_name='rock7',
            name='surfaceHoleDepth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='露天孔深'),
        ),
        migrations.AlterField(
            model_name='rock7',
            name='surfaceSuperDeep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='露天超深'),
        ),
    ]
