# Generated by Django 4.1.3 on 2023-08-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0014_alter_rock7_surfacearraypitch_and_more'),
    ]

   # operations = [
   #     migrations.AlterField(
   #         model_name='rock9',
   #         name='stopeExplosiveType',
   #         field=models.CharField(blank=True, max_length=255, null=True, verbose_name='炸药类型'),
   #    ),
   # ]
