# Generated by Django 4.2.5 on 2023-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0015_alter_rock9_stopeexplosivetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('schema_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='方案名称')),
                ('pdf_file', models.FileField(upload_to='pdf_files/', verbose_name='pdf文件')),
            ],
            options={
                'verbose_name': '工程数据库中的露天采矿',
                'verbose_name_plural': '工程数据库中的露天采矿',
            },
        ),
    ]
