# Generated by Django 4.2.5 on 2023-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0016_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='image_file_blast_heap',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='images-blast-heap/', verbose_name='爆堆'),
        ),
        migrations.AddField(
            model_name='schema',
            name='image_file_damage',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='images-damage/', verbose_name='损伤'),
        ),
        migrations.AddField(
            model_name='schema',
            name='image_file_vibration',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='images-vibration/', verbose_name='振动'),
        ),
        migrations.AddField(
            model_name='schema',
            name='image_file_wall_surface',
            field=models.ImageField(default='path/to/default_image.jpg', upload_to='images-wall-surface/', verbose_name='壁面'),
        ),
    ]
