# Generated by Django 4.2.5 on 2023-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0017_schema_image_file_blast_heap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='velocity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='振动速度'),
        ),
    ]
