# Generated by Django 4.2.5 on 2023-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0018_schema_velocity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('seg_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='分段名称')),
                ('tunnel_name', models.CharField(max_length=255, verbose_name='巷道名称')),
                ('image_img', models.ImageField(default='path/to/default_image.jpg', upload_to='images-img/', verbose_name='分段图片')),
            ],
            options={
                'verbose_name': '工程数据库中的地底下矿',
                'verbose_name_plural': '工程数据库中的地底下矿',
            },
        ),
        migrations.AlterField(
            model_name='schema',
            name='velocity',
            field=models.CharField(default='0', max_length=255, verbose_name='振动速度'),
        ),
    ]
