# Generated by Django 4.2.5 on 2023-10-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0020_tunnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema2',
            fields=[
                ('schema_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='方案名称')),
                ('pdf_file', models.FileField(upload_to='pdf_files/', verbose_name='pdf文件')),
                ('velocity', models.CharField(default='0', max_length=255, verbose_name='振动速度')),
                ('image_file_vibration', models.ImageField(default='path/to/default_image.jpg', upload_to='images-vibration/', verbose_name='振动')),
                ('image_file_damage', models.ImageField(default='path/to/default_image.jpg', upload_to='images-damage/', verbose_name='损伤')),
                ('image_file_blast_heap', models.ImageField(default='path/to/default_image.jpg', upload_to='images-blast-heap/', verbose_name='爆堆')),
                ('image_file_wall_surface', models.ImageField(default='path/to/default_image.jpg', upload_to='images-wall-surface/', verbose_name='壁面')),
            ],
            options={
                'verbose_name': '工程数据库中的露天采矿',
                'verbose_name_plural': '工程数据库中的露天采矿',
            },
        ),
    ]
