# Generated by Django 4.2.5 on 2023-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0022_ka'),
    ]

    operations = [
        migrations.CreateModel(
            name='KA2',
            fields=[
                ('k_a_value', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='KA值')),
            ],
            options={
                'verbose_name': '工程数据库中的KA值',
                'verbose_name_plural': '工程数据库中的KA值',
            },
        ),
    ]
