# Generated by Django 4.2.5 on 2023-10-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataBaseApp', '0023_ka2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ka',
            name='is_match',
            field=models.CharField(default='0', max_length=255, verbose_name='是否拟合参数'),
        ),
        migrations.AddField(
            model_name='ka2',
            name='is_match',
            field=models.CharField(default='0', max_length=255, verbose_name='是否拟合参数'),
        ),
    ]
